version: '3.4'
services:
  myeth:
    build: .
    container_name: myeth
    image: myeth-image
    hostname: myeth
    ports:
     - "8545:8545"
     - "8546:8546"
    tty: true
    volumes:
     - ./build:/build
    networks:
    - eth-network
  
  myeth1:
    build: .
    container_name: myeth1
    image: myeth-image
    hostname: myeth1
    ports:
     - "8645:8545"
     - "8646:8546"
    tty: true
    volumes:
     - ./build:/build
    networks:
    - eth-network
networks:
  eth-network:
    driver: bridge
