version: '3.4'
services:
  myeth:
    build: .
    container_name: myeth
    image: myeth-image
    ports:
     - "8500:8500"
     - "8545:8545"
     - "8546:8546"
     - "30303:30303"
    tty: true
    volumes:
     - ./build:/build
#    - swarm-data:/
    networks:
    - eth-network
  
#  goeth:
#    build: build/go-ethereum/.
#    container_name: go-eth
#    image: go-eth-image
networks:
  eth-network:
    driver: bridge
#volumes:
#    swarm-data: